[versions]
agp = "8.12.3"
maven_publish = "0.35.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven_publish" }
signing = { id = "org.gradle.signing" }